# Docker Secrets Management Configuration

version: '3.8'

services:
  # Secrets-enabled backend
  backend:
    build: ./backend
    container_name: url-backend-secure
    environment:
      - NODE_ENV=production
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
      - REDIS_URL_FILE=/run/secrets/redis_url
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - API_KEY_FILE=/run/secrets/api_key
    secrets:
      - mongodb_uri
      - redis_url
      - jwt_secret
      - api_key
    networks:
      - secure-network

  # Vault for secrets management (for production)
  vault:
    image: vault:latest
    container_name: vault-server
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
      - ./security/vault-config:/vault/config
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - secure-network

  # Secret rotation service
  secret-rotator:
    build: ./security/secret-rotator
    container_name: secret-rotator
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=myroot
    depends_on:
      - vault
    networks:
      - secure-network

# Docker secrets
secrets:
  mongodb_uri:
    external: true
  redis_url:
    external: true
  jwt_secret:
    external: true
  api_key:
    external: true

volumes:
  vault-data:

networks:
  secure-network:
    driver: bridge
